# Generated by Django 2.2.2 on 2021-12-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20211219_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='private_key',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='ballance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=50),
        ),
    ]
