# Generated by Django 2.2.2 on 2021-12-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20211219_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='public_key',
            field=models.CharField(max_length=200),
        ),
    ]
